// <auto-generated />
using System;
using GameStore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Api.Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    partial class GameStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("GameStore.Api.Models.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleasedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameStore.Api.Models.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Battle Royale"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sandbox"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MOBA"
                        },
                        new
                        {
                            Id = 4,
                            Name = "FPS"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Battle Royale/Party"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Social Deduction"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Action RPG"
                        },
                        new
                        {
                            Id = 9,
                            Name = "MMORPG"
                        },
                        new
                        {
                            Id = 10,
                            Name = "FPS/MMORPG"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 12,
                            Name = "PvPvE Shooter"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Card Game"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Tactical Shooter"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Horror/Co-op"
                        });
                });

            modelBuilder.Entity("GameStore.Api.Models.Entities.Game", b =>
                {
                    b.HasOne("GameStore.Api.Models.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
